/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCajero;

import java.awt.Color;

/**
 *
 * @author jamt_
 */
public class ccMenuRecargaa extends javax.swing.JInternalFrame {

    /**
     * Creates new form ccMenuRecargaa
     */
    public static int monto;
    
    public ccMenuRecargaa() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        txtMontoRecarga.setEditable(false);
        monto = ccdOtroMontoRecarga.otroMonto;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel20 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel100 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel50 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel200 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel500 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelOtroMonto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMontoRecarga = new javax.swing.JTextField();
        panelConfirmarRecarga = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Recarga");

        panel20.setBackground(new java.awt.Color(153, 153, 153));
        panel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel20MouseMoved(evt);
            }
        });
        panel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel20MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel20MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("S/. 20");

        javax.swing.GroupLayout panel20Layout = new javax.swing.GroupLayout(panel20);
        panel20.setLayout(panel20Layout);
        panel20Layout.setHorizontalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel20Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel20Layout.setVerticalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        panel100.setBackground(new java.awt.Color(153, 153, 153));
        panel100.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel100MouseMoved(evt);
            }
        });
        panel100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel100MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel100MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("S/. 100");

        javax.swing.GroupLayout panel100Layout = new javax.swing.GroupLayout(panel100);
        panel100.setLayout(panel100Layout);
        panel100Layout.setHorizontalGroup(
            panel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel100Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panel100Layout.setVerticalGroup(
            panel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel100Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        panel50.setBackground(new java.awt.Color(153, 153, 153));
        panel50.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel50MouseMoved(evt);
            }
        });
        panel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel50MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel50MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("S/. 50");

        javax.swing.GroupLayout panel50Layout = new javax.swing.GroupLayout(panel50);
        panel50.setLayout(panel50Layout);
        panel50Layout.setHorizontalGroup(
            panel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel50Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel50Layout.setVerticalGroup(
            panel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel50Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        panel200.setBackground(new java.awt.Color(153, 153, 153));
        panel200.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel200MouseMoved(evt);
            }
        });
        panel200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel200MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel200MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("S/. 200");

        javax.swing.GroupLayout panel200Layout = new javax.swing.GroupLayout(panel200);
        panel200.setLayout(panel200Layout);
        panel200Layout.setHorizontalGroup(
            panel200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel200Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel200Layout.setVerticalGroup(
            panel200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel200Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        panel500.setBackground(new java.awt.Color(153, 153, 153));
        panel500.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel500MouseMoved(evt);
            }
        });
        panel500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel500MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel500MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("S/. 500");

        javax.swing.GroupLayout panel500Layout = new javax.swing.GroupLayout(panel500);
        panel500.setLayout(panel500Layout);
        panel500Layout.setHorizontalGroup(
            panel500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel500Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel500Layout.setVerticalGroup(
            panel500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel500Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );

        panelOtroMonto.setBackground(new java.awt.Color(153, 153, 153));
        panelOtroMonto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOtroMontoMouseMoved(evt);
            }
        });
        panelOtroMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOtroMontoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOtroMontoMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Otro monto");

        javax.swing.GroupLayout panelOtroMontoLayout = new javax.swing.GroupLayout(panelOtroMonto);
        panelOtroMonto.setLayout(panelOtroMontoLayout);
        panelOtroMontoLayout.setHorizontalGroup(
            panelOtroMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtroMontoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelOtroMontoLayout.setVerticalGroup(
            panelOtroMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtroMontoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Monto a Recargar:");

        txtMontoRecarga.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMontoRecarga.setBorder(null);

        panelConfirmarRecarga.setBackground(new java.awt.Color(51, 255, 51));
        panelConfirmarRecarga.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelConfirmarRecargaMouseMoved(evt);
            }
        });
        panelConfirmarRecarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelConfirmarRecargaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelConfirmarRecargaMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Confirmar Recarga");

        javax.swing.GroupLayout panelConfirmarRecargaLayout = new javax.swing.GroupLayout(panelConfirmarRecarga);
        panelConfirmarRecarga.setLayout(panelConfirmarRecargaLayout);
        panelConfirmarRecargaLayout.setHorizontalGroup(
            panelConfirmarRecargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarRecargaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(19, 19, 19))
        );
        panelConfirmarRecargaLayout.setVerticalGroup(
            panelConfirmarRecargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarRecargaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel100, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOtroMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelConfirmarRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMontoRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOtroMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(panelConfirmarRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel20MouseClicked
        // TODO add your handling code here:
        panel20.setBackground(new Color(185,185,185));
        monto = 20;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }//GEN-LAST:event_panel20MouseClicked

    private void panel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel20MouseExited
        // TODO add your handling code here:
        panel20.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panel20MouseExited

    private void panel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel20MouseMoved
        // TODO add your handling code here:
        panel20.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panel20MouseMoved

    private void panel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel50MouseClicked
        // TODO add your handling code here:
        panel50.setBackground(new Color(185,185,185));
        monto = 50;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }//GEN-LAST:event_panel50MouseClicked

    private void panel50MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel50MouseExited
        // TODO add your handling code here:
        panel50.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panel50MouseExited

    private void panel50MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel50MouseMoved
        // TODO add your handling code here:
        panel50.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panel50MouseMoved

    private void panel100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel100MouseClicked
        // TODO add your handling code here:
        panel100.setBackground(new Color(185,185,185));
        monto = 100;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }//GEN-LAST:event_panel100MouseClicked

    private void panel100MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel100MouseExited
        // TODO add your handling code here:
        panel100.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panel100MouseExited

    private void panel100MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel100MouseMoved
        // TODO add your handling code here:
        panel100.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panel100MouseMoved

    private void panel200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel200MouseClicked
        // TODO add your handling code here:
        panel200.setBackground(new Color(185,185,185));
        monto = 200;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }//GEN-LAST:event_panel200MouseClicked

    private void panel200MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel200MouseExited
        // TODO add your handling code here:
        panel200.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panel200MouseExited

    private void panel200MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel200MouseMoved
        // TODO add your handling code here:
        panel200.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panel200MouseMoved

    private void panel500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel500MouseClicked
        // TODO add your handling code here:
        panel500.setBackground(new Color(185,185,185));
        monto = 500;
        txtMontoRecarga.setText("");
        txtMontoRecarga.setText("S/. "+monto);
    }//GEN-LAST:event_panel500MouseClicked

    private void panel500MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel500MouseExited
        // TODO add your handling code here:
        panel500.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panel500MouseExited

    private void panel500MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel500MouseMoved
        // TODO add your handling code here:
        panel500.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panel500MouseMoved

    private void panelOtroMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOtroMontoMouseClicked
        // TODO add your handling code here:
        panelOtroMonto.setBackground(new Color(185,185,185));
        ccdOtroMontoRecarga otroMon = new ccdOtroMontoRecarga();
        bbPrincipal.escritorio.add(otroMon);
        otroMon.toFront();
        otroMon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelOtroMontoMouseClicked

    private void panelOtroMontoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOtroMontoMouseExited
        // TODO add your handling code here:
        panelOtroMonto.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panelOtroMontoMouseExited

    private void panelOtroMontoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOtroMontoMouseMoved
        // TODO add your handling code here:
        panelOtroMonto.setBackground(new Color(185,185,185));
    }//GEN-LAST:event_panelOtroMontoMouseMoved

    private void panelConfirmarRecargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelConfirmarRecargaMouseClicked
        // TODO add your handling code here:
        panelConfirmarRecarga.setBackground(new Color(142,255,142));
        cdConfirmarRecargaa confReca = new cdConfirmarRecargaa();
        bbPrincipal.escritorio.add(confReca);
        confReca.toFront();
        confReca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelConfirmarRecargaMouseClicked

    private void panelConfirmarRecargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelConfirmarRecargaMouseExited
        // TODO add your handling code here:
        panelConfirmarRecarga.setBackground(new Color(51,255,51));
    }//GEN-LAST:event_panelConfirmarRecargaMouseExited

    private void panelConfirmarRecargaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelConfirmarRecargaMouseMoved
        // TODO add your handling code here:
        panelConfirmarRecarga.setBackground(new Color(142,255,142));
    }//GEN-LAST:event_panelConfirmarRecargaMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel100;
    private javax.swing.JPanel panel20;
    private javax.swing.JPanel panel200;
    private javax.swing.JPanel panel50;
    private javax.swing.JPanel panel500;
    private javax.swing.JPanel panelConfirmarRecarga;
    private javax.swing.JPanel panelOtroMonto;
    private javax.swing.JTextField txtMontoRecarga;
    // End of variables declaration//GEN-END:variables
}
