/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCajero;

import Conexion.ConexionSQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jamt_
 */
public class eeMenuDevolucionn extends javax.swing.JInternalFrame {

    /**
     * Creates new form eeMenuDevolucionn
     */
    public static String codVA;
    
    public eeMenuDevolucionn() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    void obtenerCodVA(){
        codVA = txtCodVA.getText();
    }
    
    int obtenerIdVA(){
        int idVAA = 0;
        String consul="SELECT * FROM VoucherAlquiler WHERE idVA=(SELECT MAX(idVA) FROM VoucherAlquiler WHERE idCliente="+bbPrincipal.idCliente+" AND estadoVA="+1+")";
        try {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(consul);
            while(rs.next())
            {
                idVAA= rs.getInt("idVA");
            }
            System.out.println("idVA: " + idVAA);
        } catch (Exception e) {
            System.out.println("Error obtener idVA: " + e);
        }
        return idVAA;
    }
    
    String obtnerCodVADB(){
        int idVA = obtenerIdVA();
        String codVADB = "";
        String consul="SELECT * FROM VoucherAlquiler WHERE idVA="+idVA;
        try {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(consul);
            if(rs.next())
            {
                codVADB= rs.getString("codigoVA");
            }
            System.out.println("codVADB: " + codVADB);
        } catch (Exception e) {
            System.out.println("Error obtener codVADB: " + e);
        }
        return codVADB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodVA = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Devolucion");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese Codigo de Voucher:");

        txtCodVA.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        btnSiguiente.setBackground(new java.awt.Color(51, 255, 51));
        btnSiguiente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodVA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        obtenerCodVA();
        if(codVA.equals("")){
            JOptionPane.showMessageDialog(null, "Campo Vacio", "Importante",1);
            txtCodVA.setText("");
        }else{
            String codVABD = obtnerCodVADB();
            if(codVA.equals(codVABD)){
                efConfirmarDevolucionn confDevo = new efConfirmarDevolucionn();
                bbPrincipal.escritorio.add(confDevo);
                confDevo.toFront();
                confDevo.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Codigo no existe", "Importante",1);
                txtCodVA.setText("");
            }
        }
        
        
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodVA;
    // End of variables declaration//GEN-END:variables
Conexion.ConexionSQL cc = new ConexionSQL();
Connection cn= ConexionSQL.conexionn();
}
